version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-35
    depends_on:
      api:
        condition: service_started
    ports:
      - 80:80

  api:
    image: vikver74/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      todolist_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: vikver74/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - ./.env
    depends_on:
      todolist_db:
        condition: service_healthy
    command: python manage.py migrate

  todolist_db:
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
