version: "3.9"

services:
  todolist_pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      HOST: localhost
      PORT: 5432
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


