version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    depends_on:
      api:
        condition: service_started
    ports:
      - 80:80

  api:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      todolist_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      todolist_db:
        condition: service_healthy
    command: python manage.py migrate

  bot:
    build:
      context: .
    restart: always
    env_file:
      - ./.env
    depends_on:
      todolist_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: python manage.py runbot

  todolist_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
